# Generated by Django 5.1 on 2024-09-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodReceipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='type',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON-VEG', 'Non-Vegetarian')], default='VEG', max_length=7),
            preserve_default=False,
        ),
    ]
